[package]
name = "cairo-sys-rs"
license = "MIT"
links = "cairo"
authors = ["The Gtk-rs Project Developers"]
homepage = "http://gtk-rs.org/"
description = "FFI bindings to libcairo"
version = "0.7.0"
keywords = ["cairo", "ffi", "gtk-rs", "gnome"]
repository = "https://github.com/gtk-rs/cairo"
build = "build.rs"

[lib]
name = "cairo_sys"

[features]
dox = ["x11/dox"]
v1_12 = []
v1_14 = ["v1_12"]
xlib = ["x11"]
png = []
xcb = []
use_glib = ["glib-sys", "gobject-sys", "glib"]

[dependencies]
libc = "0.2"

[dependencies.glib]
optional = true
version = "0.6.0"

[dependencies.glib-sys]
optional = true
version = "0.7.0"

[dependencies.gobject-sys]
optional = true
version = "0.7.0"

[dependencies.x11]
optional = true
version = "2.16"
features = ["xlib"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.2", features = ["windef"] }

[build-dependencies]
pkg-config = "0.3.7"

[patch.crates-io]
glib-sys = { git = "https://github.com/EPashkin/rust-gnome-sys" }
gobject-sys = { git = "https://github.com/EPashkin/rust-gnome-sys" }
